# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see <https://docs.haskellstack.org/en/stable/travis_ci/>.

# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

# Caching so the next build will be faster
cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p "$HOME/.local/bin"
  - export "PATH=$HOME/.local/bin:$PATH"
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
  # - stack install stack-hpc-coveralls
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-8.0.1.tar.bz2 | tar xj -C "$HOME/.local/bin"

install:
  # Build dependencies
  - stack -j2 --no-terminal --install-ghc test --only-dependencies

script:
  # Build the package, its tests, and its docs and run the tests
  - stack -j2 --no-terminal test --haddock --no-haddock-deps --coverage

after_script:
  # Collect and submit coverage information
  - shc wavetoy7 wavetoy7-test-suite
